//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenAEC.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenAEC.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Addin
        ///Manager.
        /// </summary>
        public static string AddinManager_ButtonText {
            get {
                return ResourceManager.GetString("AddinManager_ButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is an OpenAEC apps, Addin Manager..
        /// </summary>
        public static string AddinManager_Description {
            get {
                return ResourceManager.GetString("AddinManager_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddinManager.
        /// </summary>
        public static string AddinManager_Name {
            get {
                return ResourceManager.GetString("AddinManager_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenAEC_AddinManagerSettings.txt.
        /// </summary>
        public static string AddinManager_SettingsFileName {
            get {
                return ResourceManager.GetString("AddinManager_SettingsFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap addinManager16 {
            get {
                object obj = ResourceManager.GetObject("addinManager16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap addinManager32 {
            get {
                object obj = ResourceManager.GetObject("addinManager32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Delete
        ///Backups.
        /// </summary>
        public static string DeleteBackups_ButtonText {
            get {
                return ResourceManager.GetString("DeleteBackups_ButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete all family &amp; project backup files from current document location..
        /// </summary>
        public static string DeleteBackups_Description {
            get {
                return ResourceManager.GetString("DeleteBackups_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to first save this file for us to be able to obtain its location..
        /// </summary>
        public static string DeleteBackups_FileNotSavedException {
            get {
                return ResourceManager.GetString("DeleteBackups_FileNotSavedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will delete all backup files from the current document&apos;s folder, including :
        ///- family backups (.rfa)
        ///- project backups (.rvt)
        ///.
        /// </summary>
        public static string DeleteBackups_InstructionDescription {
            get {
                return ResourceManager.GetString("DeleteBackups_InstructionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete all backup files ?.
        /// </summary>
        public static string DeleteBackups_MainInstruction {
            get {
                return ResourceManager.GetString("DeleteBackups_MainInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete all backup files..
        /// </summary>
        public static string DeleteBackups_MessageTitle {
            get {
                return ResourceManager.GetString("DeleteBackups_MessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Backups.
        /// </summary>
        public static string DeleteBackups_Name {
            get {
                return ResourceManager.GetString("DeleteBackups_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, keep backup files..
        /// </summary>
        public static string DeleteBackups_NoDontDelete {
            get {
                return ResourceManager.GetString("DeleteBackups_NoDontDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete all project and family backup files from current file&apos;s location..
        /// </summary>
        public static string DeleteBackups_ProgressFormTitle {
            get {
                return ResourceManager.GetString("DeleteBackups_ProgressFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, delete them!.
        /// </summary>
        public static string DeleteBackups_YesDelete {
            get {
                return ResourceManager.GetString("DeleteBackups_YesDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap deleteBackups16 {
            get {
                object obj = ResourceManager.GetObject("deleteBackups16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap deleteBackups32 {
            get {
                object obj = ResourceManager.GetObject("deleteBackups32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create pushbutton due to invalid arguments..
        /// </summary>
        public static string Error_PushbuttonInvalidArgs {
            get {
                return ResourceManager.GetString("Error_PushbuttonInvalidArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon OpenAEC {
            get {
                object obj = ResourceManager.GetObject("OpenAEC", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenAEC.
        /// </summary>
        public static string Ribbon_TabName {
            get {
                return ResourceManager.GetString("Ribbon_TabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management.
        /// </summary>
        public static string Ribbon_TabNameManagement {
            get {
                return ResourceManager.GetString("Ribbon_TabNameManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenAEC.Ribbon.Availability.
        /// </summary>
        public static string Ribbon_ZeroDocAvailability {
            get {
                return ResourceManager.GetString("Ribbon_ZeroDocAvailability", resourceCulture);
            }
        }
    }
}
